### ISSUE TITLE
fatal error: google/protobuf/port_def.inc: No such file or directory

### ISSUE THREAD

**Issue by linClubs** [thfylsty/FastBEV-TensorRT#1]
/home/xxx/fy/code/cpp_cuda_centernet/protobuf/aarch64/protobuf

my pc has port_def.inc list：

locate port_def.inc

/home/lin/software/miniconda3/envs/eiseg/lib/python3.8/site-packages/tensorflow/include/external/upb/upb/port_def.inc
/home/lin/software/miniconda3/envs/eiseg/lib/python3.8/site-packages/tensorflow/include/google/protobuf/port_def.inc
/home/lin/software/miniconda3/envs/th1.11/lib/python3.8/site-packages/tensorflow/include/external/upb/upb/port_def.inc
/home/lin/software/miniconda3/envs/th1.11/lib/python3.8/site-packages/tensorflow/include/google/protobuf/port_def.inc
/home/lin/software/opencv-4.6.0/3rdparty/protobuf/src/google/protobuf/port_def.inc

which one do me use ？ or how to install the protobuf

**Comment by thfylsty** [comment]
i have upload the protobuf.zip in filefold, you can down and unzip it to use. modify the protobuf link in makefile. （uploading  wait few mins）

**Comment by linClubs** [comment]
谢谢

**Comment by xll426** [comment]
可以提供一个onnx和数据吗 编译的时候过不了

**Comment by thfylsty** [comment]
会有的，周末之前吧，这两天事情实在多。稍等一下

**Comment by thfylsty** [comment]
> 可以提供一个onnx和数据吗 编译的时候过不了

临时更新了一个，但是模型推理效果不好。没有训练正常（好像哪个配置错了）。但是也能推理测测玩玩了。先试试叭。

```shell

mkdir workspace
mv ./nuscenes/* ./workspace/
make bev -j8


```
