### ISSUE TITLE
关于时序的问题

### ISSUE THREAD

**Issue by fengguibinyn** [thfylsty/FastBEV-TensorRT#3]
fastbev 是融合了历史3帧 算上当前一共4个输出 下面是我按你给出的逻辑写出的代码，是否有问题， volume_history1 ,2 ,3 是workspace上的内存，存放历史特征

        float_t *volume_history1 = (float_t *)workspace + lutsize;
        float_t *volume_history2 =  volume_history1 + lutsize;
        float_t *volume_history3 =  volume_history2 + lutsize;
        

        cudaMemcpy(outputs[1].ptr<float>(), volume_history1 , lutsize * sizeof(float_t), cudaMemcpyDeviceToDevice);
        cudaMemcpy(outputs[2].ptr<float>(), volume_history2 , lutsize * sizeof(float_t), cudaMemcpyDeviceToDevice);
        cudaMemcpy(outputs[3].ptr<float>(), volume_history3 , lutsize * sizeof(float_t), cudaMemcpyDeviceToDevice);
        // 投影
        backproject_LUT_GPU(features, LUT, volume_output.ptr<float>(), n_voxels_int,n_images, n_channels);

        cudaMemcpy(volume_history3, volume_history2 , lutsize * sizeof(float_t), cudaMemcpyDeviceToDevice);
        cudaMemcpy(volume_history2, volume_history1 , lutsize * sizeof(float_t), cudaMemcpyDeviceToDevice);
        cudaMemcpy(volume_history1, volume_output.ptr<float>() , lutsize * sizeof(float_t), cudaMemcpyDeviceToDevice);

**Comment by thfylsty** [comment]
> fastbev 是融合了历史3帧 算上当前一共4个输出 下面是我按你给出的逻辑写出的代码，是否有问题， volume_history1 ,2 ,3 是workspace上的内存，存放历史特征
> 
> ```
>     float_t *volume_history1 = (float_t *)workspace + lutsize;
>     float_t *volume_history2 =  volume_history1 + lutsize;
>     float_t *volume_history3 =  volume_history2 + lutsize;
>     
> 
>     cudaMemcpy(outputs[1].ptr<float>(), volume_history1 , lutsize * sizeof(float_t), cudaMemcpyDeviceToDevice);
>     cudaMemcpy(outputs[2].ptr<float>(), volume_history2 , lutsize * sizeof(float_t), cudaMemcpyDeviceToDevice);
>     cudaMemcpy(outputs[3].ptr<float>(), volume_history3 , lutsize * sizeof(float_t), cudaMemcpyDeviceToDevice);
>     // 投影
>     backproject_LUT_GPU(features, LUT, volume_output.ptr<float>(), n_voxels_int,n_images, n_channels);
> 
>     cudaMemcpy(volume_history3, volume_history2 , lutsize * sizeof(float_t), cudaMemcpyDeviceToDevice);
>     cudaMemcpy(volume_history2, volume_history1 , lutsize * sizeof(float_t), cudaMemcpyDeviceToDevice);
>     cudaMemcpy(volume_history1, volume_output.ptr<float>() , lutsize * sizeof(float_t), cudaMemcpyDeviceToDevice);
> ```

我觉得相当对~，大概这是个这么情况，因为trt 会分配好后会一直保留workspace这块空间，理论上（实际上我简单测了下也是）可以拿到history 。
lutsize 只是长度，需要乘上变量类型大小。

还有两个点，

1，第一次进入是没有history的，可以直接用它随机的内存值。跑几帧后就正常了。或者判断是否是第一次，如果是，就copy当前帧。

2，减少如此大量的cudaMemcpy。用一些flag int 来记录索引和初始化。
```c++

        int *flag=  volume_history2 + 4*sizeof(int);
        if(flag[0] != 1){
            flag[0] = 1; //如果flag[0] 不是1 那就初始化，表示第一次进来（但万一这片内存正好是1怎么办呢？）

            flag[1] = 0; // flag[1] history 1 的idx
            flag[2] = 1; // flag[2] history 2 的idx
            flag[3] = 2; // flag[3] history 3 的idx
        }
        else{
            flag[1] = (flag[1]+1) %2 ; //history idx 往后挪
            flag[2] = (flag[2]+1) %2 ;
            flag[3] = (flag[3]+1) %2 ;
        }
        float *start_ptr = (float_t *)workspace + lutsize*(int32_t); 

        float_t *volume_history1 = start_ptr + lutsize*(float_t)*flag[1];
        float_t *volume_history2 = start_ptr + lutsize*(float_t)*flag[2];
        float_t *volume_history3 = start_ptr + lutsize*(float_t)*flag[3];

```

**Comment by thfylsty** [comment]
其实 LUT 本身也应该是固定值。算出来后保存到txt。然后用pytorch读进去。直接导onnx的时候一起传入。和projection一样。

**Comment by fengguibinyn** [comment]
非常感谢您的回复！关于您提出的两个问题，我也考虑了一下，首先第一帧问题，打算直接随机值赋值，第二问题 大量的cudaMemcpy，不知道如和根据您给代码去改写，麻烦您能细写一下吗

**Comment by thfylsty** [comment]
没事，第二个先不管，先跑起来再说。



第二个其实就是想优化下，history 常驻某个地址。
比如，第一次是 [1],[2],[3] 对应 上一帧，上二帧，上三帧
然后更新， 
上三帧 丢弃，空间赋值当前帧，作为下一次的“上一帧”
上一帧 变成了  上二帧
上二帧 变成了  上三帧
内存里保存的顺序就是
[2],[3],[1]


意思就是根据索引来找上三帧的 顺序。可以减少两次拷贝。

**Comment by fengguibinyn** [comment]
好的 感谢
